### ISSUE TITLE
webSocket auto reconnect doesn't work if socket is closed

### ISSUE THREAD

**Issue by yivlad** [wevm/viem#2325]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/viem/issues) for the bug I encountered.

### Viem Version

2.13.1

### Current Behavior

We use `webSocket` transport in our frontend app. After some period of inactivity browsers automatically close the web socket connections. When a user leaves the tab open and gets back after a while, `webSocket` transport is unable to recover from the socket `CLOSED` state and requests keep failing.

### Expected Behavior

`webSocket` transport creates new connection in place of the closed one.

### Steps To Reproduce

Minimal reproducible example using only `viem`:

```ts
import { createPublicClient, parseAbi, webSocket } from "viem";

const client = createPublicClient({
  transport: webSocket(
    "wss://mainnet.infura.io/ws/v3/84842078b09946638c03157f83405213"
  ),
});

const blockNumber = await client.readContract({
  abi: parseAbi(["function getBlockNumber() view returns (uint256)"]),
  address: "0xca11bde05977b3631167028862be2a173976ca11",
  functionName: "getBlockNumber",
});

console.log({
  blockNumber
});

(await client.transport.getRpcClient()).socket.close(); // simulate closing by browser

await client.readContract({
  abi: parseAbi(["function getBlockNumber() view returns (uint256)"]),
  address: "0xca11bde05977b3631167028862be2a173976ca11",
  functionName: "getBlockNumber",
});
```

In the provided code the second request fails because the web socket connection is closed.

**Comment by badgerdf** [comment]
Same issue on backend side (nest.js framework). Moreover, viem doesn't notify about socket disconnect/reconnect by logs, just looks like that websocket is just stuck without any reason.
 
Here is client creation code.
```
createPublicClient({
      chain: Viem.utils.extractChain(CONFIG.CHAIN_ID),
      transport: webSocket(CONFIG.RPC.WS, {
        reconnect: true,
        retryCount: Infinity,
        retryDelay: 1000,
        timeout: 1000
      }),
    })
```

**Comment by flux0uz** [comment]
Same problem for us, impossible to index via websocket, no disconnection errors and no automatic reconnection. This is really annoying, because we're going to have to listen via http and explode our alchemy quotas!

**Comment by 0x33dm** [comment]
> Same problem for us, impossible to index via websocket, no disconnection errors and no automatic reconnection. This is really annoying, because we're going to have to listen via http and explode our alchemy quotas! Do you know if a fix is in the works?

You can increase the number of reconnect attempts (https://viem.sh/docs/clients/transports/websocket.html), but I don't see a way to be notified of the connection status or how to use WSS + Viem in a reliable way for indexing...

**Comment by izayl** [comment]
in my case, it because the backend nginx timeout setting

when I subscribe a topic with indexed topics, it may have long time without response, if backend setting a max timeout, the socket will be closed, return code 1006('Abnormal Closure')

there are two way to resolve this issue:

1. verify all the CloseEvent code, apply onError logic first to reuse current reconnect logic. Yes, it will not trigger onerror like above timeout case

2. implement keepalive

I just implement the keep-alive feature

#2516 

happy to receive some feedbacks

**Comment by 0x33dm** [comment]
> happy to receive some feedbacks

One thing I miss/couldn't find is a way to subscribe to connection events, like "connected," "disconnected," or "error," in order to make the application more self-aware.

During my initial tests with WS transport, I found that WS would disconnect and fail silently, and my application would stop.

i think either i'm missing something from the documentation or there is room for improvement.

**Comment by izayl** [comment]
> > happy to receive some feedbacks很高兴收到一些反馈
> 
> One thing I miss/couldn't find is a way to subscribe to connection events, like "connected," "disconnected," or "error," in order to make the application more self-aware.我错过/找不到的一件事是订阅连接事件的方法，例如“已连接”、“已断开连接”或“错误”，以便使应用程序更具自我意识。
> 
> During my initial tests with WS transport, I found that WS would disconnect and fail silently, and my application would stop.在我对 WS 传输的初始测试中，我发现 WS 将断开连接并默默地失败，并且我的应用程序将停止。
> 
> i think either i'm missing something from the documentation or there is room for improvement.我认为要么我从文档中遗漏了一些东西，要么还有改进的空间。

I think you can get the `socket` first, and subscribe by yourself for advanced usage

```ts
const WS_URL = ''
const webSocketClient = createPublicClient({
  chain: mainnet,
  transport: webSocket(WS_URL)
})

const socketClient = await getSocketClient(WS_URL)
const socket = socketClient.socket
```

**Comment by 0x33dm** [comment]
> ```ts
> getWebSocketRpcClient
> ```

interesting i didn't find docs for this function on viem website, but my VS CODE finds it.

thank you.

**Comment by jxom** [comment]
Fixed via https://github.com/wevm/viem/commit/44281e85e28f893df6e722ebadfe74b2a9bf93e2

**Comment by 0x33dm** [comment]
> Fixed via [44281e8](https://github.com/wevm/viem/commit/44281e85e28f893df6e722ebadfe74b2a9bf93e2)

^ amazing

---

Would be possible to also add documentation on how to listen for connection status on the websocket so services that rely on monitoring each block can recover quickly?

From @izayl i got the hint to look for `getWebSocketRpcClient` but i havent' played with it yet.

thank you

**Comment by flux0uz** [comment]
It seems that the problem persists, we updated our staging environment yesterday and this morning the events are not caught... So the websocket connection must have closed...
No errors on the watchContractEvent onError callback.

**Comment by izayl** [comment]
@flux0uz u can try with following code to verify the ws close reason first, see what's the code of close event

replace the `ws_rpc_url` to yourselfs 

```ts

if (publicClient.transport.type === 'webSocket') {
  const client = await getWebSocketRpcClient(ws_rpc_url!)
  const socket = client.socket
  socket.addEventListener('close', (e) => {
    console.error('websocket closed', e)
  })
}
```

**Comment by flux0uz** [comment]
Thanks @izayl, no errors were detected on the socket "close" event. I've just realised that the problem is with the fallback([]). By removing the fallback on the public provider used to listen to events, everything works normally!

@jxom
The fallback option for websocket transport is breaking the auto-reconnect and not throwing any errors.

**Comment by flux0uz** [comment]
Back to this issue! Another test this morning, listening to the sockets close (with @izayl code). No close log, and we don't receive any events. PublicProvider with a single websocket connection via Alchemy and no fallback.

**Comment by izayl** [comment]
> Back to this issue! Another test this morning, listening to the sockets close (with @izayl code). No close log, and we don't receive any events. PublicProvider with a single websocket connection via Alchemy and no fallback.

double check your ABI, maybe has wrong order or missed `indexed`

**Comment by flux0uz** [comment]
Nop works correctly with http transport, but uses a ton of our Alchemy quota!

**Comment by flux0uz** [comment]
Now listening `message` on dev environment, first one is OK then keep getting:
`[Symbol(kData)]: '{"id":null,"jsonrpc":"2.0","error":{"code":-32700,"message":"Parse error"}}'`

**Comment by justefg** [comment]
i confirm. it doesn't work. please run a minimum reproducible for **at least** 2 hours before merging.

**Comment by justefg** [comment]
You might want to take a look at alchemy's ws implementation. tested it and its rock solid with no connection breaking. Looking at your fix why do use `ping` if it's not supported by an json rpc api? I suggest using `net_version` or `chainId` like alchemy does
https://github.com/alchemyplatform/alchemy-sdk-js/blob/master/src/api/alchemy-websocket-provider.ts#L746-L757

rpc endpoints:
https://docs.alchemy.com/reference/net-version
https://www.quicknode.com/docs/ethereum/net_version

**Comment by justefg** [comment]
Sorry for a bit of spamming but I really need this feature as it's blocking us from moving forward. This seems to be a common issue for web3 libraries -- ethers having the same issue and no ETA. Web3 js claims to have resolved the issue recently. 
https://github.com/web3/web3.js/issues/6968

If you need my help I'll be glad to assist.

**Comment by jxom** [comment]
I published [a release](https://github.com/wevm/viem/releases/tag/viem%402.18.5) this morning which makes socket closure handling a bit more robust. 

If that doesn't solve your issue, please favor opening a new issue with a minimal reproducible example over replying to this closed issue.

**Comment by justefg** [comment]
Unfortunately, it still doesn't work. I created another ticket with steps on how to reproduce the issue.
https://github.com/wevm/viem/issues/2563
